### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by jkillz2020**
1st PR

### CODE REVIEW

**Comment by williamhickok11** [comment]
I'm getting errors in my console. I also don't see any fight logic in this pull request.

**Comment by jkillz2020** [comment]
@williamhickok11 I believe it is at MVP.  Fight logic working on attack click.  Weapon select is working.

**Comment by zoeames** [comment]
i don't see this working.  first time i played one of my players died instantly.  every combination i have played since then nothing shows on the screen.

**Comment by zoeames** [comment]
also try to make this more modular.  use IIFE's and break up your code.   having one JS file makes things complicated

**Comment by jkillz2020** [comment]
:(. It worked on mine.

**Comment by zoeames** [comment]
👍

**Comment by jkillz2020** [comment]
🙏

**Pull request merged**
